name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    runs:
      using: 'node16'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm install c8 --save-dev
      - run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
